name: Auto Update WWE Results
on:
  schedule:
    - cron: '0 9 * * *' # Runs every morning at 9:00 AM
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "WWE Tracker Bot"
          git config --global user.email "bot@wwetracker.com"
          git add index.html
          git commit -m "Auto-update match results"
          git push
